# Generated by Django 3.2.6 on 2022-03-03 12:17

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogposts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', tinymce.models.HTMLField()),
                ('date', models.DateField(auto_now_add=True, verbose_name='')),
                ('author', models.CharField(default='Indian Nerds', max_length=25)),
                ('about', models.CharField(default='this blog contens a wide information about topic . you can get wide knowledge of it after you read it. It will cover all your queries abot this topic', max_length=500)),
                ('thumbnail', models.ImageField(default='/thumbnail/icon.jpg', upload_to='thumbnail/')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='SOME STRING', max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(default=0, max_length=12)),
                ('desc', models.TextField()),
            ],
        ),
    ]
