# Generated by Django 3.2.6 on 2022-03-03 12:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogposts',
            name='id',
        ),
        migrations.AddField(
            model_name='blogposts',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
