# Generated by Django 3.2.6 on 2022-03-03 12:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usite', '0002_auto_20220303_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid3, editable=False, primary_key=True, serialize=False),
        ),
    ]
