# Generated by Django 3.2.6 on 2022-03-03 12:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usite', '0003_alter_blogposts_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False),
        ),
    ]
