# Generated by Django 3.2.6 on 2022-03-03 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usite', '0009_alter_blogposts_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='uuid',
            field=models.BigAutoField(editable=False, max_length=4, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
